services:
  client:
    container_name: front-client
    build: .
    restart: on-failure
    ports:
      - "4200:80"

  api:
    container_name: front-api
    image: ghcr.io/organizationmercury/mercury-api:develop
    restart: on-failure
    depends_on:
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports: 
      - "8080:8080"
    environment:
      NEO4J_URI: "neo4j://neo4j:7687"
      NEO4J_PASSWORD: $NEO4J_PASSWORD
      NEO4J_USERNAME: $NEO4J_USERNAME
      POSTGRES_CONNECTION_STRING: Host=postgres;Port=5432;Database=$POSTGRES_DB;Password=$POSTGRES_PASSWORD;User Id=$POSTGRES_USER
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      JWT_ISSUER: $JWT_ISSUER
      JWT_KEY: $JWT_KEY

  minio:
    container_name: front-minio
    image: minio/minio
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server --console-address :9001 /data

  neo4j:
    container_name: front-neo4j
    image: neo4j:5.16-community
    restart: on-failure
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD

  postgres:
    container_name: front-postgres
    image: postgres:16.2
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

volumes:
  minio_data: