name: Publish

on:
  push: 
    branches: [ master, develop ]

env:
  REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change working directory
        run: cd ClientApp/app
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Restore project
        run: npm ci

      - name: Build project
        run: npm run build

  publish-image:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.github_token }}

      - name: Build and Push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/organizationmercury/mercury-client${{ github.ref_name == 'develop' && '-dev' || '' }}
